// <auto-generated />
namespace SelfEduV2.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tryagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131432091_tryagain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
